# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello']

# %% ../00_core.ipynb 3
def foo(): pass

# %% ../00_core.ipynb 5
def say_hello(to):
    """
    Say hello to somebody.
    Args:
    - to: the person to greet
    """
    return f'Hello {to}!'
